#!/usr/bin/env python3
"""Job titles organized by wealth level for realistic employee assignment."""

# Job titles organized by wealth level (low to high income)
# Each tier has job titles that match the salary ranges

JOB_TITLES_BY_WEALTH_TIER = {
    "low_income": [
        "Janitor",
        "Custodian", 
        "Receptionist",
        "Security Guard",
        "Maintenance Worker",
        "Cleaner",
        "Kitchen Assistant",
        "Warehouse Worker",
        "Retail Associate",
        "Data Entry Clerk",
        "Mail Clerk",
        "Parking Attendant",
        "Groundskeeper",
        "Cafeteria Worker",
        "Office Assistant",
        "File Clerk",
        "Receptionist",
        "Customer Service Representative",
        "Call Center Agent",
        "Administrative Assistant",
        "Secretary",
        "Office Clerk",
        "Shipping Clerk",
        "Inventory Clerk",
        "Cashier",
        "Sales Associate",
        "Customer Support Specialist",
        "Help Desk Technician",
        "IT Support Specialist",
        "Junior Accountant",
        "Bookkeeper",
        "Payroll Clerk",
        "HR Assistant",
        "Marketing Assistant",
        "Sales Assistant",
        "Research Assistant",
        "Lab Technician",
        "Quality Control Inspector",
        "Production Worker",
        "Assembly Line Worker",
        "Machine Operator",
        "Forklift Driver",
        "Delivery Driver",
        "Courier",
        "Taxi Driver",
        "Bus Driver",
        "Concierge",
        "Bellhop",
        "Housekeeper",
        "Nanny"
    ],
    
    "small_investor": [
        "Accountant",
        "Financial Analyst",
        "Business Analyst",
        "Project Coordinator",
        "Marketing Coordinator",
        "HR Coordinator",
        "Operations Coordinator",
        "Sales Representative",
        "Account Manager",
        "Customer Success Manager",
        "Product Manager",
        "Content Manager",
        "Social Media Manager",
        "Digital Marketing Specialist",
        "SEO Specialist",
        "Graphic Designer",
        "Web Developer",
        "Software Developer",
        "Database Administrator",
        "Network Administrator",
        "Systems Administrator",
        "IT Manager",
        "Operations Manager",
        "Facilities Manager",
        "Procurement Manager",
        "Supply Chain Coordinator",
        "Logistics Coordinator",
        "Quality Assurance Manager",
        "Training Manager",
        "Compliance Officer",
        "Risk Analyst",
        "Insurance Agent",
        "Real Estate Agent",
        "Loan Officer",
        "Credit Analyst",
        "Investment Advisor",
        "Financial Planner",
        "Tax Advisor",
        "Legal Assistant",
        "Paralegal",
        "Research Analyst",
        "Market Research Analyst",
        "Data Analyst",
        "Business Intelligence Analyst",
        "UX Designer",
        "UI Designer",
        "Product Designer",
        "Technical Writer",
        "Technical Support Manager",
        "Customer Success Manager"
    ],
    
    "medium_investor": [
        "Senior Accountant",
        "Senior Financial Analyst",
        "Senior Business Analyst",
        "Senior Project Manager",
        "Program Manager",
        "Portfolio Manager",
        "Senior Marketing Manager",
        "Brand Manager",
        "Senior HR Manager",
        "Talent Acquisition Manager",
        "Senior Operations Manager",
        "Regional Manager",
        "District Manager",
        "Senior Sales Manager",
        "Key Account Manager",
        "Senior Product Manager",
        "Product Marketing Manager",
        "Senior Digital Marketing Manager",
        "Marketing Director",
        "Creative Director",
        "Art Director",
        "Senior Web Developer",
        "Senior Software Developer",
        "Lead Developer",
        "Software Architect",
        "Senior Database Administrator",
        "Senior Network Administrator",
        "Senior Systems Administrator",
        "IT Director",
        "Chief Technology Officer",
        "Senior Operations Manager",
        "Operations Director",
        "Senior Facilities Manager",
        "Senior Procurement Manager",
        "Supply Chain Manager",
        "Senior Logistics Manager",
        "Senior Quality Assurance Manager",
        "Senior Training Manager",
        "Senior Compliance Officer",
        "Senior Risk Analyst",
        "Senior Insurance Agent",
        "Senior Real Estate Agent",
        "Senior Loan Officer",
        "Senior Credit Analyst",
        "Senior Investment Advisor",
        "Senior Financial Planner",
        "Senior Tax Advisor",
        "Senior Legal Assistant",
        "Senior Paralegal",
        "Senior Research Analyst",
        "Senior Market Research Analyst",
        "Senior Data Analyst",
        "Senior Business Intelligence Analyst",
        "Senior UX Designer",
        "Senior UI Designer",
        "Senior Product Designer",
        "Senior Technical Writer",
        "Senior Technical Support Manager",
        "Senior Customer Success Manager"
    ],
    
    "high_investor": [
        "Chief Executive Officer",
        "Chief Operating Officer",
        "Chief Financial Officer",
        "Chief Technology Officer",
        "Chief Marketing Officer",
        "Chief Human Resources Officer",
        "Chief Information Officer",
        "Chief Risk Officer",
        "Chief Compliance Officer",
        "Chief Legal Officer",
        "Chief Revenue Officer",
        "Chief Strategy Officer",
        "Chief Innovation Officer",
        "Chief Data Officer",
        "Chief Security Officer",
        "Chief Product Officer",
        "Chief Customer Officer",
        "Chief Experience Officer",
        "Chief Digital Officer",
        "Chief Transformation Officer",
        "President",
        "Vice President",
        "Senior Vice President",
        "Executive Vice President",
        "Managing Director",
        "General Manager",
        "Regional Director",
        "Country Manager",
        "Division Manager",
        "Business Unit Manager",
        "Senior Director",
        "Director",
        "Associate Director",
        "Principal",
        "Partner",
        "Managing Partner",
        "Senior Partner",
        "Equity Partner",
        "Senior Consultant",
        "Principal Consultant",
        "Senior Advisor",
        "Board Member",
        "Independent Director",
        "Executive Director",
        "Non-Executive Director",
        "Chairman",
        "Vice Chairman",
        "Lead Director",
        "Audit Committee Chair",
        "Compensation Committee Chair",
        "Nominating Committee Chair",
        "Governance Committee Chair",
        "Risk Committee Chair",
        "Technology Committee Chair",
        "Investment Committee Chair",
        "Strategic Planning Committee Chair",
        "Executive Committee Member",
        "Senior Executive",
        "C-Suite Executive",
        "Senior Leadership Team Member"
    ]
}

def get_job_titles_for_tier(wealth_tier: str) -> list[str]:
    """Get job titles for a specific wealth tier."""
    return JOB_TITLES_BY_WEALTH_TIER.get(wealth_tier, [])

def get_all_job_titles() -> list[str]:
    """Get all job titles across all wealth tiers."""
    all_titles = []
    for tier_titles in JOB_TITLES_BY_WEALTH_TIER.values():
        all_titles.extend(tier_titles)
    return all_titles

def get_job_title_count() -> int:
    """Get total number of job titles available."""
    return len(get_all_job_titles())
